#!/bin/sh
# Test the post-worktree-create extension point in git-clone-worktree.
#
# It was also in git-nb until 2026-09-04, when git-nb was retired: `wt switch --create` does that
# job, and the equivalent trigger for that path is a worktrunk post-switch hook, which is user
# config rather than anything this repo ships. git-clone-worktree is RETAINED -- worktrunk has no
# clone verb, so it cannot bootstrap the container layout it is then perfectly able to manage --
# and it is the only creation path left in this public repo.
#
# WHY THIS IS A PUBLIC-BASE FEATURE AT ALL. A worktree is born without hooks in the husky layout --
# `.husky/_` is generated by a dependency install and gitignored -- and git reports "no hooks"
# rather than an error, so the defect is silent from birth. Creation is the cheapest moment to say
# so. The base cannot depend on any private checker, so it offers a documented hook path and runs
# whatever is installed there.
#
# THE TWO PROPERTIES THAT MATTER, and both are asserted with a manufactured failure rather than
# reasoned about:
#   1. it FIRES, with the new worktree's absolute path;
#   2. it CANNOT break worktree creation -- absent hook and failing hook both still succeed. A
#      reporting hook that can fail a creation is a guard people route around, which is worse than
#      no guard (kb autonomy-escalation).
set -u
_TMP=${TMPDIR:-/tmp}; _TMP=${_TMP%/}
here=$(cd "$(dirname "$0")" && pwd)
clonewt="$here/../private_dot_local/bin/executable_git-clone-worktree"
tmp=$(mktemp -d "$_TMP/test-wpc.XXXXXX"); trap 'rm -rf "$tmp"' EXIT
fails=0
ok()  { printf '  ok    %s\n' "$1"; }
bad() { printf '  FAIL  %s\n     %s\n' "$1" "$2"; fails=$((fails+1)); }

g() { git -c user.email=t@t -c user.name=t -c commit.gpgsign=false "$@"; }

# An upstream repo with one commit on main, for git-clone-worktree to clone into the container
# layout it produces.
origin="$tmp/origin.git"; g init --bare -q "$origin"
seed="$tmp/seed"; g clone -q "$origin" "$seed" 2>/dev/null
( cd "$seed" && : > f && g add f && g commit -qm init && g push -q origin HEAD:refs/heads/main ) >/dev/null 2>&1

home="$tmp/home"; mkdir -p "$home/.dotlocal/hooks"
n=0
clone() { n=$((n+1)); ( cd "$tmp" && HOME="$home" bash "$clonewt" "$origin" "target$n" >/dev/null 2>&1 ); }

# --- 1. hook ABSENT: creation must still succeed ---------------------------------------------------
clone; rc=$?
if [ "$rc" -eq 0 ] && [ -d "$tmp/target1/main" ]; then ok "no hook installed: container still created"
else bad "no hook installed: creation failed" "rc=$rc"; fi

# --- 2. hook FIRES with the new worktree's absolute path -------------------------------------------
printf '#!/bin/sh\nprintf "%%s" "$1" > "%s/fired"\n' "$tmp" > "$home/.dotlocal/hooks/post-worktree-create"
chmod +x "$home/.dotlocal/hooks/post-worktree-create"
clone
if [ -f "$tmp/fired" ]; then
  got=$(cat "$tmp/fired")
  case "$got" in
    "$tmp/target2/main") ok "hook fired with the new worktree's absolute path" ;;
    *) bad "hook fired with the wrong path" "expected $tmp/target2/main, got $got" ;;
  esac
else bad "hook did not fire" "no marker written"; fi

# --- 3. hook FAILS: creation must STILL succeed (advisory only) ------------------------------------
# The manufactured red for the property that matters most. A reporting hook able to abort a creation
# is a guard that gets routed around, which is worse than no guard at all.
printf '#!/bin/sh\necho "hook says no" >&2\nexit 1\n' > "$home/.dotlocal/hooks/post-worktree-create"
chmod +x "$home/.dotlocal/hooks/post-worktree-create"
clone; rc=$?
if [ "$rc" -eq 0 ] && [ -d "$tmp/target3/main" ]; then ok "failing hook did not break creation"
else bad "a failing hook broke creation" "rc=$rc"; fi

# --- 4. hook present but NOT executable: still must not break --------------------------------------
chmod -x "$home/.dotlocal/hooks/post-worktree-create"
clone; rc=$?
if [ "$rc" -eq 0 ] && [ -d "$tmp/target4/main" ]; then ok "non-executable hook ignored, creation succeeded"
else bad "non-executable hook broke creation" "rc=$rc"; fi

printf '\n'
[ "$fails" -eq 0 ] && printf 'all post-worktree-create checks passed\n' || printf '%s check(s) FAILED\n' "$fails"
exit $([ "$fails" -eq 0 ] && echo 0 || echo 1)
