#!/bin/sh
# Test the post-worktree-create extension point in git-nb and git-clone-worktree.
#
# WHY THIS IS A PUBLIC-BASE FEATURE AT ALL. A worktree is born without hooks in the husky layout --
# `.husky/_` is generated by a dependency install and gitignored -- and git reports "no hooks"
# rather than an error, so the defect is silent from birth. Creation is the cheapest moment to say
# so. The base cannot depend on any private checker, so it offers a documented hook path and runs
# whatever is installed there.
#
# THE TWO PROPERTIES THAT MATTER, and both are asserted with a manufactured failure rather than
# reasoned about:
#   1. it FIRES, with the new worktree's absolute path;
#   2. it CANNOT break worktree creation -- absent hook and failing hook both still succeed. A
#      reporting hook that can fail a creation is a guard people route around, which is worse than
#      no guard (kb autonomy-escalation).
set -u
_TMP=${TMPDIR:-/tmp}; _TMP=${_TMP%/}
here=$(cd "$(dirname "$0")" && pwd)
gitnb="$here/../private_dot_local/bin/executable_git-nb"
tmp=$(mktemp -d "$_TMP/test-wpc.XXXXXX"); trap 'rm -rf "$tmp"' EXIT
fails=0
ok()  { printf '  ok    %s\n' "$1"; }
bad() { printf '  FAIL  %s\n     %s\n' "$1" "$2"; fails=$((fails+1)); }

g() { git -c user.email=t@t -c user.name=t -c commit.gpgsign=false "$@"; }

# A bare-container layout: <c>/.bare + <c>/.git pointing at it + <c>/main, which is what git-nb
# derives its target directory from.
origin="$tmp/origin.git"; g init --bare -q "$origin"
seed="$tmp/seed"; g clone -q "$origin" "$seed" 2>/dev/null
( cd "$seed" && : > f && g add f && g commit -qm init && g push -q origin HEAD:refs/heads/main ) >/dev/null 2>&1

c="$tmp/container"; mkdir -p "$c"
g clone -q --bare "$origin" "$c/.bare" 2>/dev/null
printf 'gitdir: ./.bare\n' > "$c/.git"
g -C "$c" config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
g -C "$c" fetch -q origin 2>/dev/null
g -C "$c" worktree add -q "$c/main" main 2>/dev/null

home="$tmp/home"; mkdir -p "$home/.dotlocal/hooks"

# git-nb's ONE-argument form (`git-nb <branch>`) checks out an existing branch into a sibling
# worktree, which is the shape this fleet actually uses. Pre-create the branches in the bare so each
# case below has one to claim. (The two-argument form passes $2 as the worktree PATH rather than a
# start-point, so `git-nb <branch> main` collides with the existing main worktree -- noted, not
# changed here: this suite is about the post-create hook, not about git-nb's argument handling.)
for b in wt-absent wt-fires wt-failing wt-noexec; do g -C "$c/.bare" branch "$b" main 2>/dev/null; done

# --- 1. hook ABSENT: creation must still succeed ---------------------------------------------------
out=$(cd "$c/main" && HOME="$home" bash "$gitnb" wt-absent 2>&1); rc=$?
if [ "$rc" -eq 0 ] && [ -d "$c/wt-absent" ]; then ok "no hook installed: worktree still created"
else bad "no hook installed: creation failed" "rc=$rc; $out"; fi

# --- 2. hook FIRES with the new worktree's absolute path -------------------------------------------
printf '#!/bin/sh\nprintf "%%s" "$1" > "%s/fired"\n' "$tmp" > "$home/.dotlocal/hooks/post-worktree-create"
chmod +x "$home/.dotlocal/hooks/post-worktree-create"
out=$(cd "$c/main" && HOME="$home" bash "$gitnb" wt-fires 2>&1); rc=$?
if [ -f "$tmp/fired" ]; then
  got=$(cat "$tmp/fired")
  case "$got" in
    "$c/wt-fires") ok "hook fired with the new worktree's absolute path" ;;
    *) bad "hook fired with the wrong path" "expected $c/wt-fires, got $got" ;;
  esac
else bad "hook did not fire" "rc=$rc; $out"; fi

# --- 3. hook FAILS: creation must STILL succeed (advisory only) ------------------------------------
# The manufactured red for the property that matters most. A reporting hook able to abort a worktree
# creation is a guard that gets routed around.
printf '#!/bin/sh\necho "hook says no" >&2\nexit 1\n' > "$home/.dotlocal/hooks/post-worktree-create"
chmod +x "$home/.dotlocal/hooks/post-worktree-create"
out=$(cd "$c/main" && HOME="$home" bash "$gitnb" wt-failing 2>&1); rc=$?
if [ "$rc" -eq 0 ] && [ -d "$c/wt-failing" ]; then ok "failing hook did not break worktree creation"
else bad "a failing hook broke worktree creation" "rc=$rc; $out"; fi

# --- 4. hook present but NOT executable: still must not break --------------------------------------
chmod -x "$home/.dotlocal/hooks/post-worktree-create"
out=$(cd "$c/main" && HOME="$home" bash "$gitnb" wt-noexec 2>&1); rc=$?
if [ "$rc" -eq 0 ] && [ -d "$c/wt-noexec" ]; then ok "non-executable hook ignored, creation succeeded"
else bad "non-executable hook broke creation" "rc=$rc; $out"; fi

printf '\n'
[ "$fails" -eq 0 ] && printf 'all post-worktree-create checks passed\n' || printf '%s check(s) FAILED\n' "$fails"
exit $([ "$fails" -eq 0 ] && echo 0 || echo 1)
