#!/bin/sh
# Tests for install-test-gate: the opt-in commit gate a private layer installs into its own source
# repository. Real commits in scratch repositories, with the machine's global git config (and so its
# configured hooks) switched off, so only the gate under test runs.
set -u
here=$(cd "$(dirname "$0")" && pwd)
tool="$here/../private_dot_local/bin/executable_install-test-gate"
t=${TMPDIR:-/tmp}; t=${t%/}
tmp=$(mktemp -d "$t/test-install-test-gate.XXXXXX"); trap 'rm -rf "$tmp"' EXIT
export GIT_CONFIG_GLOBAL="$tmp/gitconfig"; : > "$GIT_CONFIG_GLOBAL"
git config --global user.name t; git config --global user.email t@t.invalid; git config --global commit.gpgsign false
pass=0; fail=0
ok()  { pass=$((pass + 1)); echo "ok:   $1"; }
bad() { fail=$((fail + 1)); echo "FAIL: $1"; }
check() { if eval "$2"; then ok "$1"; else bad "$1"; fi; }

mkrepo() { # mkrepo <dir> <suite-exit-code>
  rm -rf "$1"; git init -q "$1"; mkdir -p "$1/tests" "$1/docs" "$1/bin"
  printf '#!/bin/sh\necho suite-ran\nexit %s\n' "$2" > "$1/tests/run-all.sh"
  echo seed > "$1/README.md"; git -C "$1" add -A; git -C "$1" commit -qm seed --no-verify
}
commit_one() { # commit_one <repo> <path> -> exit status of the commit
  echo x >> "$1/$2"; git -C "$1" add "$2"; git -C "$1" commit -qm change > "$tmp/out" 2>&1
}

# Not a git checkout: nothing to do, nothing written.
mkdir -p "$tmp/plain"
sh "$tool" "$tmp/plain" --label x --skip-var SKIP_X > "$tmp/out" 2>&1; rc=$?
check "not a git checkout: exit 0, nothing written" '[ "$rc" = 0 ] && [ ! -e "$tmp/plain/.git" ]'

# Usage errors.
sh "$tool" > "$tmp/out" 2>&1; rc=$?
check "no arguments: usage, exit 2" '[ "$rc" = 2 ]'
mkrepo "$tmp/r" 1
sh "$tool" "$tmp/r" --label x --skip-var 'not a var' > "$tmp/out" 2>&1; rc=$?
check "a skip variable that is not a variable name is refused" '[ "$rc" = 2 ] && [ ! -e "$tmp/r/.git/hooks/pre-commit" ]'

# Installed with the default scope: everything but documentation runs the suite.
sh "$tool" "$tmp/r" --label "my layer" --skip-var SKIP_MY_TESTS > "$tmp/out" 2>&1; rc=$?
check "install: exit 0, an executable pre-commit written" '[ "$rc" = 0 ] && [ -x "$tmp/r/.git/hooks/pre-commit" ]'
commit_one "$tmp/r" bin/tool; rc=$?
check "a failing suite refuses a commit of a non-doc file" '[ "$rc" != 0 ] && grep -q "my layer" "$tmp/out" && grep -q SKIP_MY_TESTS "$tmp/out"'
git -C "$tmp/r" reset -q
commit_one "$tmp/r" docs/page.md; rc=$?
check "a documentation-only commit skips the suite" '[ "$rc" = 0 ] && ! grep -q suite-ran "$tmp/out"'
echo x >> "$tmp/r/bin/tool"; git -C "$tmp/r" add bin/tool
SKIP_MY_TESTS=1 git -C "$tmp/r" commit -qm skipped > "$tmp/out" 2>&1; rc=$?
check "the skip variable lets a deliberate WIP commit through" '[ "$rc" = 0 ]'
printf '#!/bin/sh\nexit 0\n' > "$tmp/r/tests/run-all.sh"; git -C "$tmp/r" add tests/run-all.sh
commit_one "$tmp/r" bin/tool; rc=$?
check "a passing suite lets the commit through" '[ "$rc" = 0 ]'

# Installed with --paths: only matching staged paths run the suite.
mkrepo "$tmp/p" 1
sh "$tool" "$tmp/p" --label p --skip-var SKIP_P --paths '^(bin/|tests/)' > /dev/null 2>&1
commit_one "$tmp/p" other.txt; rc=$?
check "--paths: a non-matching path is not gated" '[ "$rc" = 0 ]'
commit_one "$tmp/p" bin/tool; rc=$?
check "--paths: a matching path is gated" '[ "$rc" != 0 ]'

# Never overwrites a pre-commit it did not write; re-installing over its own is fine.
mkrepo "$tmp/f" 0
printf '#!/bin/sh\n# someone else s hook\nexit 0\n' > "$tmp/f/.git/hooks/pre-commit"
sh "$tool" "$tmp/f" --label f --skip-var SKIP_F > "$tmp/out" 2>&1; rc=$?
check "a foreign pre-commit is refused and left untouched" '[ "$rc" = 1 ] && grep -q "someone else" "$tmp/f/.git/hooks/pre-commit"'
sh "$tool" "$tmp/r" --label "my layer" --skip-var SKIP_MY_TESTS > "$tmp/out" 2>&1; rc=$?
check "re-installing over its own hook succeeds" '[ "$rc" = 0 ]'
mkrepo "$tmp/l" 0
printf '#!/bin/sh\n# dotfiles-overlay pre-commit (generated by run_onchange_install-overlay-hooks.sh).\n' > "$tmp/l/.git/hooks/pre-commit"
sh "$tool" "$tmp/l" --label l --skip-var SKIP_L > "$tmp/out" 2>&1; rc=$?
check "the hook its predecessor generated is replaced" '[ "$rc" = 0 ] && grep -q "generated by install-test-gate" "$tmp/l/.git/hooks/pre-commit"'

echo "passed: $pass   failed: $fail"
[ "$fail" -eq 0 ]
